WIP: link the Strategy and Order managers
KomodoPlatform/antara-makerbot pull request #48
Opened 2019-08-23 08:00 UTC by DCPRevere

2019-08-25 08:15 UTC, Milerius requested changes

2019-08-25 08:15 UTC, Milerius commented on src/price/service.price.platform.hpp
> +    class abstract_price_service_platform
I really disagree as using abstract class for price_service_platform (there is only one service)

Use template class instead

2019-08-25 08:15 UTC, Milerius commented on src/strategy_manager/strategy.manager.tests.cpp
> +        auto sm = strategy_manager(ps, om);
strategy_manager can be templated on the implementation class such as:

`strategy_manager<price_service_platform_fake>(ps, om);`

2019-08-25 08:15 UTC, Milerius commented on src/strategy_manager/strategy.manager.tests.cpp
> +        auto sm = strategy_manager(ps, om);
Abstract classes and interfaces are useful when you have to manipulate several, not when you have to mock a class. The templates will do the trick here

2019-08-26 09:23 UTC, DCPRevere commented
@Milerius I've made the change to use a template instead of the abstract class.

2019-08-26 16:13 UTC, merged